export const ENV_VARS = {
  SERVER_GLOBAL_PREFIX: 'SERVER_GLOBAL_PREFIX',
  SERVER_PORT: 'SERVER_PORT',
  CLIENT_URI: 'CLIENT_URI',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_NAME: 'DATABASE_NAME',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRES: 'ACCESS_TOKEN_EXPIRES',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRES: 'REFRESH_TOKEN_EXPIRES'
};
